# Generated by Django 3.2.7 on 2022-01-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='datetime created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='datetime updated')),
                ('pdf', models.FileField(max_length=160, upload_to=None, verbose_name='PDF')),
                ('_hash', models.BinaryField(max_length=16, null=True, verbose_name='MD5 hash')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
