# Generated by Django 4.0.3 on 2022-03-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='topic',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Icon Literature'), (2, 'About Us'), (3, 'About Syntax'), (4, 'About Literacy')], default=1),
        ),
    ]
