# Generated by Django 4.0.1 on 2022-02-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_pdf_title_pdf_topic_alter_pdf_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='topic',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bookshelf'), (2, 'About Us'), (3, 'About Syntax'), (4, 'About Literacy'), (5, 'Notes')], default=1, verbose_name='Topic'),
        ),
    ]
