# Generated by Django 4.0.3 on 2022-04-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_pdf_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='topic',
            field=models.PositiveSmallIntegerField(choices=[(1, 'About'), (2, 'Icon Literature'), (3, 'Personal')], default=1),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='topic',
            field=models.PositiveSmallIntegerField(choices=[(1, 'About'), (2, 'Icon Literature'), (3, 'Personal')], default=1),
        ),
    ]
