# Generated by Django 4.0.1 on 2022-02-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_alter_pdf_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='datetime created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='datetime updated')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='topic',
        ),
        migrations.AddField(
            model_name='pdf',
            name='categories',
            field=models.ManyToManyField(related_name='Category', to='pdf.Category'),
        ),
    ]
