# Generated by Django 4.0.1 on 2022-02-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0004_category_remove_pdf_topic_pdf_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='categories',
            field=models.ManyToManyField(to='pdf.Category'),
        ),
    ]
