# Generated by Django 3.2.3 on 2021-05-19 01:44

import api.dictionary.models.category
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='datetime created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='datetime updated')),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='icons')),
                ('_hash', models.BinaryField(default=None, max_length=16, null=True)),
                ('category', models.SmallIntegerField(choices=[(api.dictionary.models.category.Category['ADJECTIVE'], 'Adjective'), (api.dictionary.models.category.Category['ADVERB'], 'Adverb'), (api.dictionary.models.category.Category['CONNECTIVE'], 'Connective'), (api.dictionary.models.category.Category['NOUN'], 'Noun'), (api.dictionary.models.category.Category['PREPOSITION'], 'Preposition'), (api.dictionary.models.category.Category['PUNCTUATION'], 'Punctuation'), (api.dictionary.models.category.Category['VERB_IRREGULAR'], 'Irregular Verb'), (api.dictionary.models.category.Category['VERB_MODAL'], 'Modal Verb'), (api.dictionary.models.category.Category['VERB_REGULAR'], 'Regular Verb'), (api.dictionary.models.category.Category['VERB_TWO_PART'], 'Two-Part Verb')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MP3',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='datetime created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='datetime updated')),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('data', models.FileField(upload_to='mp3', verbose_name='MP3')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='datetime created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='datetime updated')),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('data', models.TextField(verbose_name='JSON data')),
                ('icon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dictionary.icon')),
                ('mp3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dictionary.mp3', verbose_name='MP3')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
