# Generated by Django 3.2.3 on 2021-05-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedSearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='datetime created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='datetime updated')),
                ('mw', models.CharField(max_length=64)),
                ('wn', models.CharField(max_length=64)),
                ('data', models.TextField(verbose_name='JSON data')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
