# Generated by Django 3.2.3 on 2021-06-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='img'),
        ),
    ]
