# Generated by Django 3.2.3 on 2021-07-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20210702_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='part_speech',
            field=models.PositiveSmallIntegerField(choices=[(0, 'no category'), (1, 'adjectives'), (2, 'adverbs'), (3, 'connectives'), (4, 'nouns'), (5, 'prepositions'), (6, 'punctuation'), (7, 'verbs 2-part'), (8, 'verbs irregular'), (9, 'verbs modals'), (10, 'verbs regular')], default=0),
        ),
        migrations.AlterField(
            model_name='icon',
            name='_hash',
            field=models.BinaryField(max_length=16, null=True, verbose_name='MD5 hash'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='descriptor',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='icon',
            name='tense',
            field=models.PositiveSmallIntegerField(choices=[(0, 'no tense'), (1, 'present'), (2, 'present participle'), (3, 'past'), (4, 'past participle')], default=0),
        ),
        migrations.AlterField(
            model_name='mp3',
            name='_hash',
            field=models.BinaryField(max_length=16, null=True, verbose_name='MD5 hash'),
        ),
    ]
