# Generated by Django 3.2.3 on 2021-06-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_cachedsearchterm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachedsearchterm',
            name='data',
        ),
        migrations.AddField(
            model_name='cachedsearchterm',
            name='_data',
            field=models.BinaryField(default=b'', verbose_name='JSON data (in binary)'),
        ),
    ]
