# Generated by Django 3.2.3 on 2021-06-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_icon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
