# Generated by Django 3.2.3 on 2021-06-03 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20210602_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cachedsearchterm',
            old_name='_data',
            new_name='data',
        ),
    ]
