# Generated by Django 3.2.3 on 2021-06-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_icon_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp3',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
