# Generated by Django 3.2.3 on 2021-06-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_alter_mp3_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mp3',
            old_name='data',
            new_name='mp3',
        ),
        migrations.AddField(
            model_name='mp3',
            name='_hash',
            field=models.BinaryField(default=None, max_length=16, null=True, verbose_name='MD5 hash'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='_hash',
            field=models.BinaryField(default=None, max_length=16, null=True, verbose_name='MD5 hash'),
        ),
    ]
