# Generated by Django 3.2.3 on 2021-07-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_auto_20210721_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='descriptor',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='icon',
            name='word',
            field=models.CharField(max_length=80),
        ),
    ]
