# Generated by Django 3.2.3 on 2021-06-03 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_rename__data_cachedsearchterm_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cachedsearchterm',
            old_name='data',
            new_name='_data',
        ),
    ]
