# Generated by Django 3.2.3 on 2021-06-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_rename_data_cachedsearchterm__data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachedsearchterm',
            name='_data',
        ),
        migrations.AddField(
            model_name='cachedsearchterm',
            name='data',
            field=models.TextField(default='', verbose_name='JSON data'),
        ),
    ]
