# Generated by Django 3.2.4 on 2021-06-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_auto_20210622_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionaryentry',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='thesaurusentry',
            name='icon',
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='icons',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='dictionary.Icon'),
        ),
        migrations.AddField(
            model_name='thesaurusentry',
            name='icons',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='dictionary.Icon'),
        ),
    ]
