# Generated by Django 3.2.3 on 2021-06-03 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_auto_20210603_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachedsearchterm',
            name='data',
        ),
    ]
