# Generated by Django 3.2.3 on 2021-06-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_remove_cachedsearchterm_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedsearchterm',
            name='data',
            field=models.TextField(default='', verbose_name='JSON data'),
        ),
    ]
