# Generated by Django 3.2.3 on 2021-06-04 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_cachedsearchterm_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('json', models.TextField(default='', verbose_name='Merriam-Webster dictionary entry')),
                ('icon', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dictionary.icon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThesaurusEntry',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('json', models.TextField(default='', verbose_name='Merriam-Webster thesaurus entry')),
                ('icon', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dictionary.icon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='CachedSearchTerm',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='MP3',
        ),
        migrations.AddField(
            model_name='thesaurusentry',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.word'),
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.word'),
        ),
    ]
