# Generated by Django 3.2.3 on 2021-06-04 22:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_auto_20210604_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryentry',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='datetime created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='datetime updated'),
        ),
        migrations.AddField(
            model_name='thesaurusentry',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='datetime created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thesaurusentry',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='datetime updated'),
        ),
        migrations.AddField(
            model_name='word',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='datetime created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='datetime updated'),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='icon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.icon'),
        ),
        migrations.AlterField(
            model_name='thesaurusentry',
            name='icon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.icon'),
        ),
    ]
